modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Luncaaa/AdvancedLinks/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors = "Lucaaa"
description = '''
Create server links in the links menu!
'''
displayURL="https://modrinth.com/plugin/advancedlinks" #optional
logoFile = "assets/advancedlinks/icon.png"
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"
